name: finances
description: "A modern personal finance app with a pastel color theme."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  sqflite: ^2.2.8+4
  path: ^1.8.3
  intl: ^0.18.0
  fl_chart: ^0.70.2
  google_fonts: ^4.0.4
  shared_preferences: ^2.1.1
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Add assets if needed
  # assets:
  #   - assets/images/
  
  # Add custom fonts if needed 
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
